'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Eye, Database, Share2, Cookie, UserCheck, Mail } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-background-dark dark:to-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <Link 
            href="/" 
            className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-primary mb-6 transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back to Home
          </Link>
          <div className="flex items-center gap-4 mb-4">
            <div className="size-14 bg-primary/10 rounded-2xl flex items-center justify-center">
              <Eye className="size-7 text-primary" />
            </div>
            <div>
              <h1 className="text-3xl font-black text-gray-900 dark:text-white">Privacy Policy</h1>
              <p className="text-gray-500">Last updated: January 2026</p>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="prose prose-lg dark:prose-invert max-w-none">

          {/* Introduction */}
          <section className="mb-12">
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed text-lg">
              At HealthDoc, we take your privacy seriously. This Privacy Policy explains how we collect, use, 
              disclose, and safeguard your information when you use our medical report analysis service.
            </p>
          </section>

          {/* Information Collection */}
          <section className="mb-12 bg-white dark:bg-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-700">
            <h2 className="text-2xl font-bold mb-6 dark:text-white flex items-center gap-2">
              <Database className="size-6 text-primary" />
              Information We Collect
            </h2>
            <div className="space-y-6">
              <div>
                <h3 className="font-bold text-gray-900 dark:text-white mb-2">Personal Information</h3>
                <ul className="space-y-2 text-gray-600 dark:text-gray-300">
                  <li>• Name and email address (for account creation)</li>
                  <li>• Profile information you choose to provide</li>
                  <li>• Family member profiles you create</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-gray-900 dark:text-white mb-2">Health Information</h3>
                <ul className="space-y-2 text-gray-600 dark:text-gray-300">
                  <li>• Medical reports and lab results you upload</li>
                  <li>• Analysis results generated by our AI</li>
                  <li>• Health metrics and trends over time</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-gray-900 dark:text-white mb-2">Technical Information</h3>
                <ul className="space-y-2 text-gray-600 dark:text-gray-300">
                  <li>• Device information and browser type</li>
                  <li>• IP address and usage patterns</li>
                  <li>• Cookies and similar technologies</li>
                </ul>
              </div>
            </div>
          </section>

          {/* How We Use */}
          <section className="mb-12">
            <h2 className="text-2xl font-bold mb-6 dark:text-white flex items-center gap-2">
              <Share2 className="size-6 text-primary" />
              How We Use Your Information
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-green-50 dark:bg-green-900/20 p-6 rounded-xl border border-green-200 dark:border-green-800">
                <h3 className="font-bold text-green-800 dark:text-green-400 mb-3">We Use Your Data To:</h3>
                <ul className="space-y-2 text-green-700 dark:text-green-300 text-sm">
                  <li>✓ Provide and improve our services</li>
                  <li>✓ Analyze your medical reports</li>
                  <li>✓ Generate health insights</li>
                  <li>✓ Send important notifications</li>
                  <li>✓ Respond to your inquiries</li>
                </ul>
              </div>
              <div className="bg-red-50 dark:bg-red-900/20 p-6 rounded-xl border border-red-200 dark:border-red-800">
                <h3 className="font-bold text-red-800 dark:text-red-400 mb-3">We Never:</h3>
                <ul className="space-y-2 text-red-700 dark:text-red-300 text-sm">
                  <li>✗ Sell your personal data</li>
                  <li>✗ Share data with advertisers</li>
                  <li>✗ Use data for marketing without consent</li>
                  <li>✗ Access data without authorization</li>
                  <li>✗ Store data longer than necessary</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Cookies */}
          <section className="mb-12 bg-gray-50 dark:bg-gray-800/50 p-8 rounded-2xl">
            <h2 className="text-2xl font-bold mb-4 dark:text-white flex items-center gap-2">
              <Cookie className="size-6 text-primary" />
              Cookies & Tracking
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mb-4">
              We use essential cookies to provide our service. These include:
            </p>
            <ul className="space-y-2 text-gray-600 dark:text-gray-300">
              <li>• <strong>Authentication cookies:</strong> To keep you logged in securely</li>
              <li>• <strong>Preference cookies:</strong> To remember your settings (like dark mode)</li>
              <li>• <strong>Security cookies:</strong> To protect against unauthorized access</li>
            </ul>
            <p className="text-gray-500 dark:text-gray-400 mt-4 text-sm">
              We do not use tracking cookies or third-party analytics that compromise your privacy.
            </p>
          </section>

          {/* Your Rights */}
          <section className="mb-12">
            <h2 className="text-2xl font-bold mb-6 dark:text-white flex items-center gap-2">
              <UserCheck className="size-6 text-primary" />
              Your Privacy Rights
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mb-6">
              Depending on your location, you may have the following rights:
            </p>
            <div className="grid sm:grid-cols-3 gap-4">
              {[
                { title: 'Access', desc: 'Request a copy of your data' },
                { title: 'Correction', desc: 'Update inaccurate information' },
                { title: 'Deletion', desc: 'Request data erasure' },
                { title: 'Portability', desc: 'Export your data' },
                { title: 'Objection', desc: 'Opt-out of processing' },
                { title: 'Restriction', desc: 'Limit data usage' },
              ].map((right) => (
                <div key={right.title} className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-200 dark:border-gray-700">
                  <h3 className="font-bold text-gray-900 dark:text-white">{right.title}</h3>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">{right.desc}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Contact */}
          <section className="bg-white dark:bg-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-700">
            <h2 className="text-2xl font-bold mb-4 dark:text-white flex items-center gap-2">
              <Mail className="size-6 text-primary" />
              Contact Us
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mb-4">
              For privacy-related questions or to exercise your rights, contact us at:
            </p>
            <a 
              href="mailto:creativesimulation1@gmail.com" 
              className="inline-flex items-center gap-2 text-primary hover:underline font-medium"
            >
              creativesimulation1@gmail.com
            </a>
          </section>

        </div>
      </div>
    </div>
  );
}
